### ISSUE TITLE
Add :hover to nav bar links

### ISSUE THREAD

**Issue by xjwllmsx** [xjwllmsx/colmaracademy-fork#7]
- [x] Add a :hover selector to the links in the nav bar for increased accessibility.

**Comment by xjwllmsx** [comment]
I added the following code to the stylesheet:
```css
nav a {
    font-weight: 600;
    color: #4769b2;
    text-decoration: none;
    padding: 15px 0;
    transition: 0.3s;
}

nav a:hover {
    padding: 10px 0 5px;
    box-shadow: 0 -5px 0px #FECD45 inset;
}
```
When the cursor hovers over a link, the text raises and a yellow bar appears underneath.
